---
- name: Update web servers
    hosts: webservers
  remote_user: root

  tasks:
  - name: Ensure apache is at the latest version
    ansible.builtin.yum:
    name: httpd
    state: latest

  - name: Write the apache config file
    ansible.builtin.templatee:
      src: /srv/httpd.j2
      dest: /etc/httpd.conf

- name: Update db servers
  hosts: databases
  remote_user: root

  tasks:
  - name: Ensure postgresql is at the latest version
    ansible.windows.yum:
    name: postgresql
    state: l
